#!/bin/bash
    if (( $(echo "$1 == 0" | bc -l) ));then
       echo "scale=15;90" | bc -l
    elif (( $(echo "$1 <= 1" | bc -l) ));then
       echo "scale=15;a(sqrt((1/($1^2))-1)) * 360/(2*4*a(1))" | bc -l
    elif (( $(echo "$1 > 1" | bc -l) ));then
       echo "error"
    fi

